---

- hosts: all
  become: true
  tasks:

  - name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
    shell: cat /etc/os-release | tee /home/ansible/_os_release
    args:
      executable: /bin/bash

- hosts: all
  become: true
  tasks:

  - name: Specifying a path directly
    fetch:
      src: /home/ansible/_os_release
      dest: /home/ansible/ansible/data/_os_release-{{ inventory_hostname }}
      flat: yes 
