---

- hosts: all
  become: true
  tasks:

  - name: Copy file with owner and permission, using symbolic representation
    copy:
      src: /usr/bin/git-add
      dest: /usr/bin/git-add
      owner: root
      group: root
      mode: u=rw,g=r,o=rx
