---

- hosts: all
  become: true
  tasks:

##################################################################

  - name: update repository index for Oopta
    dnf:
      update_cache: true
    when: ansible_distribution_release == "Oopta"
     
  - name: update repository index for Maipo
    yum:
      update_cache: true
    when: ansible_distribution_release == "Maipo"

  - name: update repository index for SLES15
    community.general.zypper:
      update_cache: true
    when: ansible_distribution_release == "15-SP5"

##################################################################

  - name: upgrade all packages on Oopta
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution_release == "Oopta"

  - name: upgrade all packages on Maipo
    yum:
      name: "*"
      state: latest
    when: ansible_distribution_release == "Maipo"

  - name: upgrade all packages on SLES15
    community.general.zypper:
      name: "*"
      state: latest
    when: ansible_distribution_release == "15-SP5"

##################################################################

  - name: install the latest version of Apache on Oopta
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution_release == "Oopta"
  
  - name: install the latest version of Apache on Maipo
    yum:
      name: httpd
      state: latest
    when: ansible_distribution_release == "Maipo"
  
  - name: install the latest version of Apache on SLES15
    community.general.zypper:
      name: httpd
      state: latest
    when: ansible_distribution_release == "Oopta"



