---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache=yes

  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: remove Apache
    dnf:
      name: httpd
      state: absent
